### ISSUE TITLE
Object #<Socket> has no method 'clearLine'

### ISSUE THREAD

**Issue by jorupp** [kevva/download-status#10]
I'm getting the following issue with download-status on my build server after the 2.0 update:
    TypeError: Object #<Socket> has no method 'clearLine'
    ....\node_modules\download-status\index.js:36:16)

Do I have an out-of-date library/environment that isn't exposing clearLine or something?  It looks like b5a134e9a017d6a43b35d74cc5052b01f21002b7 is what introduced the call.

**Comment by kevva** [comment]
https://github.com/kevva/download-status/issues/9
