### ISSUE TITLE
How to report progress to remote host

### ISSUE THREAD

**Issue by gpapin** [kevva/download-status#11]
Hi, 
This is more of a question than an issue really, I wonder how to report download status to a remote webpage using socket. I'm not sure this module would be the right tool to use for that, on the other hand I don't really know how to do that using just your download module.

Another question I have is, when you create a download with multiple links does those links get downloaded at the same time or is it one by one ? This prompt the question on reporting, would the report show 30% completed overall or just the current file being downloaded ?

Thank you

**Comment by kevva** [comment]
This is not the correct module to do that, it's only a plugin for `download`, though not actively maintained anymore.
